USE [ACCOUNTS]
GO

/****** Object:  Table [dbo].[TS_BOOKINGS]    Script Date: 07/11/2025 05:26:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TS_BOOKINGS](
	[BKG_PRIMARY] [float] NOT NULL,
	[BKG_TYPE] [varchar](20) NOT NULL,
	[BKG_DESCRIPTION] [varchar](50) NOT NULL,
	[BKG_LOCATION] [varchar](50) NOT NULL,
	[BKG_DETAIL] [varchar](4000) NOT NULL,
	[BKG_STATUS] [tinyint] NOT NULL,
	[BKG_RESOURCE] [varchar](16) NOT NULL,
	[BKG_PROJECT] [varchar](10) NOT NULL,
	[BKG_COSTCENTRE] [varchar](20) NOT NULL,
	[BKG_START] [datetime] NULL,
	[BKG_END] [datetime] NULL,
	[BKG_DAYS] [float] NOT NULL,
	[BKG_NOTES] [varchar](max) NOT NULL,
	[BKG_AUTHORISED_BY] [varchar](4) NOT NULL,
	[BKG_REJECTED_REASON] [varchar](500) NOT NULL,
	[BKG_CUCODE] [varchar](50) NOT NULL,
	[BKG_ADDRESS] [varchar](500) NOT NULL,
	[BKG_PHONE] [varchar](20) NOT NULL,
	[BKG_EMAIL] [varchar](128) NOT NULL,
	[BKG_RATE] [float] NOT NULL,
	[BKG_ANALYSIS] [varchar](25) NOT NULL,
	[BKG_ROLE] [varchar](20) NULL,
	[BKG_COLOUR] [float] NOT NULL,
	[BKG_EDITED_DATE] [datetime] NULL,
	[BKG_EDITED_BY] [varchar](4) NOT NULL,
	[BKG_PO_NO] [varchar](50) NOT NULL,
	[BKG_USER1] [varchar](50) NOT NULL,
	[BKG_COMMENTS] [varchar](100) NOT NULL,
	[BKG_COLOUR_OVERRIDE] [tinyint] NOT NULL,
	[BKG_ALL_DAY] [tinyint] NOT NULL,
	[BKG_CONTACT] [varchar](30) NOT NULL,
	[BKG_COST_PRICE] [float] NOT NULL,
	[BKG_BRING_FWD] [tinyint] NOT NULL,
	[BKG_INVOICED] [tinyint] NOT NULL,
	[BKG_DISCOUNT] [float] NOT NULL,
	[BKG_PRODUCT] [varchar](100) NOT NULL,
	[BKG_OFFSITE] [tinyint] NOT NULL,
	[BGK_INV_ADDR] [float] NOT NULL,
	[BGK_COURSE_CODE] [varchar](10) NOT NULL,
	[BGK_USER_CHAR1] [varchar](30) NOT NULL,
	[BGK_USER_CHAR2] [varchar](30) NOT NULL,
	[BGK_USER_CHAR3] [varchar](30) NOT NULL,
	[BGK_USER_CHAR4] [varchar](30) NOT NULL,
	[BGK_USER_CHAR5] [varchar](30) NOT NULL,
	[BGK_USER_CHAR6] [varchar](30) NOT NULL,
	[BGK_USER_CHAR7] [varchar](30) NOT NULL,
	[BGK_USER_CHAR8] [varchar](30) NOT NULL,
	[BGK_USER_CHAR9] [varchar](30) NOT NULL,
	[BGK_USER_CHAR10] [varchar](30) NOT NULL,
	[BGK_USER_NUM1] [float] NOT NULL,
	[BGK_USER_NUM2] [float] NOT NULL,
	[BGK_USER_NUM3] [float] NOT NULL,
	[BGK_USER_NUM4] [float] NOT NULL,
	[BGK_USER_NUM5] [float] NOT NULL,
	[BGK_USER_NUM6] [float] NOT NULL,
	[BGK_USER_NUM7] [float] NOT NULL,
	[BGK_USER_NUM8] [float] NOT NULL,
	[BGK_USER_NUM9] [float] NOT NULL,
	[BGK_USER_NUM10] [float] NOT NULL,
	[BGK_USER_FLAG1] [tinyint] NOT NULL,
	[BGK_USER_FLAG2] [tinyint] NOT NULL,
	[BGK_USER_FLAG3] [tinyint] NOT NULL,
	[BGK_USER_FLAG4] [tinyint] NOT NULL,
	[BGK_USER_FLAG5] [tinyint] NOT NULL,
	[BGK_USER_FLAG6] [tinyint] NOT NULL,
	[BGK_USER_FLAG7] [tinyint] NOT NULL,
	[BGK_USER_FLAG8] [tinyint] NOT NULL,
	[BGK_USER_FLAG9] [tinyint] NOT NULL,
	[BGK_USER_FLAG10] [tinyint] NOT NULL,
	[BGK_USER_DATE1] [datetime] NULL,
	[BGK_USER_DATE2] [datetime] NULL,
	[BGK_USER_DATE3] [datetime] NULL,
	[BGK_USER_DATE4] [datetime] NULL,
	[BGK_USER_DATE5] [datetime] NULL,
	[BGK_USER_DATE6] [datetime] NULL,
	[BGK_USER_DATE7] [datetime] NULL,
	[BGK_USER_DATE8] [datetime] NULL,
	[BGK_USER_DATE9] [datetime] NULL,
	[BGK_USER_DATE10] [datetime] NULL,
	[BGK_USER_NOTES1] [text] NOT NULL,
	[BGK_USER_NOTES2] [text] NOT NULL,
	[BGK_USER_NOTES3] [text] NOT NULL,
	[BGK_USER_NOTES4] [text] NOT NULL,
	[BGK_USER_NOTES5] [text] NOT NULL,
	[BGK_USER_TIME1] [datetime] NULL,
	[BGK_USER_TIME2] [datetime] NULL,
	[BGK_USER_TIME3] [datetime] NULL,
	[BGK_USER_TIME4] [datetime] NULL,
	[BGK_USER_TIME5] [datetime] NULL,
	[BGK_REF] [varchar](30) NOT NULL,
	[BGK_REF_LINK] [varchar](30) NOT NULL,
	[BKG_DATASET] [varchar](30) NOT NULL,
	[BKG_CURRENCY] [varchar](4) NOT NULL,
	[BGK_USER_CHAR11] [varchar](30) NOT NULL,
	[BGK_USER_CHAR12] [varchar](30) NOT NULL,
	[BGK_USER_CHAR13] [varchar](30) NOT NULL,
	[BGK_USER_CHAR14] [varchar](30) NOT NULL,
	[BGK_USER_CHAR15] [varchar](30) NOT NULL,
	[BGK_USER_CHAR16] [varchar](30) NOT NULL,
	[BGK_USER_CHAR17] [varchar](30) NOT NULL,
	[BGK_USER_CHAR18] [varchar](30) NOT NULL,
	[BGK_USER_CHAR19] [varchar](30) NOT NULL,
	[BGK_USER_CHAR20] [varchar](30) NOT NULL,
	[BKG_SOW] [varchar](20) NOT NULL,
	[BKG_DATE_PUTIN] [datetime] NULL,
	[BKG_USER_PUTIN] [varchar](4) NOT NULL,
	[BKG_CANCELLED_BY] [varchar](4) NOT NULL,
	[BKG_SHADOW_DB] [varchar](50) NOT NULL,
	[BKG_SHADOW_KEY] [float] NOT NULL,
	[BKG_SPLIT_PRIMARY] [float] NOT NULL,
	[BKG_PREDECESSOR] [float] NOT NULL,
	[BKG_HAS_SUCCESSORS] [tinyint] NOT NULL,
	[BKG_LINK_TYPE] [tinyint] NOT NULL,
	[BKG_SME_CALLTRAN] [float] NOT NULL,
	[BKG_ORIGINAL_START] [datetime] NULL,
	[BKG_WP_DAYS] [float] NOT NULL,
	[BKG_MULTI_RESOURCE] [tinyint] NOT NULL,
	[BKG_UTILISATION] [float] NOT NULL,
	[BKG_CC_TASK_PRIMARY] [float] NOT NULL,
	[BKG_TIMEZONE] [varchar](100) NULL,
	[BKG_ROLE_TSSWD_PRIMARY] [float] NULL,
	[BKG_HALF_DAY] [tinyint] NOT NULL,
	[BKG_SERIES_ID] [uniqueidentifier] NOT NULL,
	[BKG_REPEAT_BOOKING_OPTIONS] [varchar](200) NULL,
 CONSTRAINT [TS_BOOKINGS_PK] PRIMARY KEY CLUSTERED 
(
	[BKG_PRIMARY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_OFFSITE]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_INV_ADDR]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_COURSE_CODE]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR1]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR2]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR3]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR4]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR5]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR6]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR7]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR8]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR9]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR10]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_NUM1]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_NUM2]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_NUM3]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_NUM4]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_NUM5]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_NUM6]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_NUM7]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_NUM8]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_NUM9]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_NUM10]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_FLAG1]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_FLAG2]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_FLAG3]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_FLAG4]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_FLAG5]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_FLAG6]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_FLAG7]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_FLAG8]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_FLAG9]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BGK_USER_FLAG10]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_NOTES1]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_NOTES2]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_NOTES3]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_NOTES4]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_NOTES5]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_REF]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_REF_LINK]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BKG_DATASET]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BKG_CURRENCY]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR11]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR12]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR13]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR14]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR15]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR16]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR17]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR18]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR19]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BGK_USER_CHAR20]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BKG_SOW]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BKG_USER_PUTIN]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BKG_CANCELLED_BY]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ('') FOR [BKG_SHADOW_DB]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_SHADOW_KEY]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_SPLIT_PRIMARY]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_PREDECESSOR]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_HAS_SUCCESSORS]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_LINK_TYPE]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_SME_CALLTRAN]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_WP_DAYS]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_MULTI_RESOURCE]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_UTILISATION]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_CC_TASK_PRIMARY]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT ((0)) FOR [BKG_HALF_DAY]
GO

ALTER TABLE [dbo].[TS_BOOKINGS] ADD  DEFAULT (0x00) FOR [BKG_SERIES_ID]
GO


USE [ACCOUNTS]
GO

/****** Object:  Table [dbo].[TS_BOOKING_TYPES]    Script Date: 07/11/2025 05:26:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TS_BOOKING_TYPES](
	[TSBK_PRIMARY] [float] NOT NULL,
	[TSBK_CODE] [varchar](20) NOT NULL,
	[TSBK_NAME] [varchar](60) NOT NULL,
	[TSBK_TYPE] [tinyint] NOT NULL,
	[TSBK_APPROVAL] [tinyint] NOT NULL,
	[TSBK_INACTIVE] [tinyint] NOT NULL,
	[TSBK_AUTO_UPDATE_TS] [tinyint] NOT NULL,
	[TSBK_R1] [tinyint] NOT NULL,
	[TSBK_R2] [tinyint] NOT NULL,
	[TSBK_R3] [tinyint] NOT NULL,
	[TSBK_REPORTS_PATH] [varchar](255) NOT NULL,
	[TSBK_CREATE_PROJ] [tinyint] NOT NULL,
	[TSBK_TEMPLATE_PROJ] [varchar](10) NOT NULL,
	[TSBK_CON_RATE_QTY_LINK] [tinyint] NOT NULL,
	[TSBK_APPLY_CON_RATE_QTY] [tinyint] NOT NULL,
	[TSBK_CONSOLIDATE_INV_LINES] [tinyint] NOT NULL,
	[TSBK_INVOICE_LINE_TYPE] [tinyint] NOT NULL,
	[TSBK_INVOICE_PRICE_ANAL] [varchar](25) NOT NULL,
	[TSBK_TOP_SECTION_HEIGHT_TYPE] [tinyint] NOT NULL,
	[TSBK_TOP_SECTION_HEIGHT] [float] NOT NULL,
	[TSBK_OBEY_WP] [tinyint] NOT NULL,
	[TSBK_OVERRIDE_RATE] [tinyint] NOT NULL,
	[TSBK_RATE] [float] NOT NULL,
	[TSBK_SOW_PROMPT] [tinyint] NOT NULL,
	[TSBK_REVERSE_PI_LINE] [tinyint] NOT NULL,
	[TSBK_INVOICE_PRICE_ANAL_METHOD] [tinyint] NOT NULL,
	[TSBK_INVOICE_PRICE_ANAL_SP] [varchar](100) NOT NULL,
	[TSBK_LOCK_SOW] [tinyint] NOT NULL,
	[TSBK_HOURLY_RATES] [tinyint] NOT NULL,
	[TSBK_SPLIT_BKG_PER_RESOURCE] [tinyint] NOT NULL,
	[TSBK_VALIDATION_METHOD] [tinyint] NOT NULL,
	[TSBK_VALIDATION_SP] [varchar](255) NOT NULL,
	[TSBK_CALL_SP_ON_SAVE] [tinyint] NOT NULL,
	[TSBK_CALL_SP_ON_SAVE_NAME] [varchar](255) NOT NULL,
	[TSBK_SME_CALL] [varchar](5) NOT NULL,
	[TSBK_CALL_SP_ON_SAVE_CLOSE_ONLY] [tinyint] NOT NULL,
	[TSBK_USE_RES_ROLE_ON_COPY_PASTE] [tinyint] NOT NULL,
	[TSBK_DONT_UPDATE_TS_WITH_COND_HRS] [tinyint] NOT NULL,
	[TSBK_AUTO_ADJUST_FOR_WP] [tinyint] NOT NULL,
	[TSBK_AUTO_ADJUST_FOR_WP_ADD_DAYS] [tinyint] NOT NULL,
	[TSBK_EDIT_TS_ON_BOOKING_EDIT] [tinyint] NOT NULL,
	[TSBK_DO_NOT_INCLUDE_IN_WHITESPACE] [tinyint] NOT NULL,
 CONSTRAINT [TS_BOOKING_TYPES_PK] PRIMARY KEY CLUSTERED 
(
	[TSBK_PRIMARY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_R1]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_R2]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_R3]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ('') FOR [TSBK_REPORTS_PATH]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_CREATE_PROJ]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ('') FOR [TSBK_TEMPLATE_PROJ]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_CON_RATE_QTY_LINK]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_APPLY_CON_RATE_QTY]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_CONSOLIDATE_INV_LINES]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_INVOICE_LINE_TYPE]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ('') FOR [TSBK_INVOICE_PRICE_ANAL]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_TOP_SECTION_HEIGHT_TYPE]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_TOP_SECTION_HEIGHT]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_OBEY_WP]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_OVERRIDE_RATE]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_RATE]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_SOW_PROMPT]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_REVERSE_PI_LINE]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_INVOICE_PRICE_ANAL_METHOD]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ('') FOR [TSBK_INVOICE_PRICE_ANAL_SP]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_LOCK_SOW]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_HOURLY_RATES]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_SPLIT_BKG_PER_RESOURCE]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_VALIDATION_METHOD]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ('') FOR [TSBK_VALIDATION_SP]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_CALL_SP_ON_SAVE]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ('') FOR [TSBK_CALL_SP_ON_SAVE_NAME]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ('') FOR [TSBK_SME_CALL]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_CALL_SP_ON_SAVE_CLOSE_ONLY]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_USE_RES_ROLE_ON_COPY_PASTE]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_DONT_UPDATE_TS_WITH_COND_HRS]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_AUTO_ADJUST_FOR_WP]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_AUTO_ADJUST_FOR_WP_ADD_DAYS]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_EDIT_TS_ON_BOOKING_EDIT]
GO

ALTER TABLE [dbo].[TS_BOOKING_TYPES] ADD  DEFAULT ((0)) FOR [TSBK_DO_NOT_INCLUDE_IN_WHITESPACE]
GO

USE [ACCOUNTS]
GO

/****** Object:  Table [dbo].[TS_BOOKING_RATES]    Script Date: 07/11/2025 05:26:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TS_BOOKING_RATES](
	[BKGR_PRIMARY] [float] NOT NULL,
	[BKGR_PROJECT] [varchar](10) NOT NULL,
	[BKGR_ANALYSIS] [varchar](25) NOT NULL,
	[BKGR_COSTCENTRE] [varchar](10) NOT NULL,
	[BKGR_DESCRIPTION] [varchar](240) NOT NULL,
	[BKGR_QTY] [float] NOT NULL,
	[BKGR_RATE] [float] NOT NULL,
	[BKGR_DISCOUNT] [float] NOT NULL,
	[BKGR_VALUE] [float] NOT NULL,
	[BKGR_BKG_PRIMARY] [float] NOT NULL,
	[BKGR_WORKLINE] [tinyint] NOT NULL,
	[BKGR_WORKSHEET] [varchar](50) NOT NULL,
	[BKGR_TSEXD_PRIMARY] [float] NOT NULL,
	[BKGR_WORKLINE_RESOURCE] [varchar](16) NOT NULL,
	[BKGR_BKRE_PRIMARY] [float] NULL,
	[BKGR_OD_PRIMARY] [float] NULL,
	[BKGR_TARGET_DB] [nchar](40) NULL,
	[BKGR_INSERT_DATE] [datetime] NULL,
	[BKRE_EDIT_DATE] [datetime] NULL,
 CONSTRAINT [TS_BOOKING_RATES_PK] PRIMARY KEY NONCLUSTERED 
(
	[BKGR_PRIMARY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TS_BOOKING_RATES] ADD  DEFAULT ((0)) FOR [BKGR_TSEXD_PRIMARY]
GO

ALTER TABLE [dbo].[TS_BOOKING_RATES] ADD  DEFAULT ('') FOR [BKGR_WORKLINE_RESOURCE]
GO

USE [ACCOUNTS]
GO

/****** Object:  Table [dbo].[TS_BOOKING_RESOURCES]    Script Date: 07/11/2025 05:27:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TS_BOOKING_RESOURCES](
	[BKRE_PRIMARY] [float] NOT NULL,
	[BKRE_BKG_PRIMARY] [float] NOT NULL,
	[BKRE_RESOURCE] [varchar](16) NOT NULL,
	[BKRE_ROLE] [varchar](20) NOT NULL,
	[BKRE_RATE] [float] NOT NULL,
	[BKRE_DISCOUNT] [float] NOT NULL,
	[BKRE_COST_PRICE] [float] NOT NULL,
	[BKRE_DATE] [datetime] NULL,
	[BKRE_MAIN] [tinyint] NOT NULL,
	[BKRE_UPDATING] [tinyint] NOT NULL,
	[BKRE_TSSWD_PRIMARY] [float] NOT NULL,
	[BKRE_SYSTEM] [tinyint] NOT NULL,
	[BKRE_UTILISATION] [float] NOT NULL,
 CONSTRAINT [TS_BOOKING_RESOURCES_PK] PRIMARY KEY CLUSTERED 
(
	[BKRE_PRIMARY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TS_BOOKING_RESOURCES] ADD  DEFAULT ((0)) FOR [BKRE_TSSWD_PRIMARY]
GO

ALTER TABLE [dbo].[TS_BOOKING_RESOURCES] ADD  DEFAULT ((0)) FOR [BKRE_SYSTEM]
GO

ALTER TABLE [dbo].[TS_BOOKING_RESOURCES] ADD  DEFAULT ((0)) FOR [BKRE_UTILISATION]
GO

